### ISSUE TITLE
Beautify the Background 

### ISSUE THREAD

**Issue by Priyanshudubey0** [Priyanshudubey0/Drum-kit#3]
**I want a beautiful background.**

**Comment by kunalsingh1301** [comment]
hey @Priyanshudubey0 can i take thsi?

**Comment by kunalsingh1301** [comment]
hey @Priyanshudubey0  can i work on it?

**Comment by ShreyaShukla03** [comment]
Hello sir, can you please assign this to me?

**Comment by priyanshubuddy** [comment]
@Priyanshudubey0 Could you assign this to me ?

**Comment by Priyanshudubey0** [comment]
Assigned this issue to @priyanshubuddy

**Comment by dubey-priyanshu** [comment]
hey @ShreyaShukla03 nice to see you here!

if you want to contribute to this amazing project, millions of developer around the world contributing to this repo,

so next step is:
there will be 3 technical DSA rounds after that there will be HR (here 5 industry experts will be taking your interview) round where we'll discussing how your salary going be transferred to my bank account. email me at codingnahiaati@batak.com.

after that wo kaan me bataunga :)
